### ISSUE TITLE
Runpy.py: runtime warning: 'bridgepoint.prebuild' 

### ISSUE THREAD

**Issue by zydsh** [zydsh/hrm#2]
I have been getting this error for a while and it didn't come in the way of compiling the models most of the time. I believe it might causes issues that appear sometimes.

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py:125: RuntimeWarning: 'bridgepoint.prebuild' found in sys.modules after import of package 'bridgepoint', but prior to execution of 'bridgepoint.prebuild'; this may result in unpredictable behaviour

**Comment by johnrwolfe** [comment]
Ciera uses a Python program, [pyxtuml](https://github.com/xtuml/pyxtuml), to compile OAL text into OAL meta-model instances, and this warning is issued by the Python3 runtime system.  The pyxtuml documentation indicates that the tool works with Python3 and pypy, but Alasdar and I are running it on Python2, and we have never seen this warning.
Perhaps running pyxtuml with Python3 requires a slightly different invocation than that provided by Ciera.  I will continue investigating and let you know what I find, but in the absence of a clear answer, consider installing Python2 and making it the default Python for your system.

**Comment by zydsh** [comment]
The issues that arise from time to time need investigation, but they are sporadic. Perhaps because I'm not sure sometimes what I'm doing. But nonetheless, I can manage to progress if I continue to maintain small feedback loops as I go. For example, fiddling with the file system behind BP's back seems to warrant unpredictable behavior. I had a spelling mistake that I fixed from the file system, which resulted in BP to behave strangely.

**Comment by johnrwolfe** [comment]
OK, I will not spend any more time on this one unless you want me to do so.  And, I recommend closing the issue if it is not longer impeding your progress.
