### ISSUE TITLE
Relate Exception: When changing package names xtuml.meta.RelateException is fired

### ISSUE THREAD

**Issue by zydsh** [zydsh/hrm#3]
This issue may relate to issue #2 . Changing the package naming resulted in the following exception:
 
xtuml.meta.RelateException: SPR_PS(Id="f0cf0b20-d2ce-4df6-8779-b7b5a949c8ed", Name='Reply', Descrip='', Action_Semantics_internal='', Suc_Pars=1, Dialect=0) or ACT_SGN(Statement_ID="37769166-a977-4428-8d90-35c99225c15c", sigNameLineNumber=0, sigNameColumn=0, ownerNameLineNumber=0, ownerNameColumn=0, ProvidedSig_Id="f0cf0b20-d2ce-4df6-8779-b7b5a949c8ed", RequiredSig_Id="00000000-0000-0000-0000-000000000000", Value_ID="00000000-0000-0000-0000-000000000000") already related across R663
[ERROR] pyxtuml exited with code 1

The full error message:

[ERROR]   warn(RuntimeWarning(msg))
[ERROR] Traceback (most recent call last):
[ERROR]   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
[ERROR]     "__main__", mod_spec)
[ERROR]   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
[ERROR]     exec(code, run_globals)
[ERROR]   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/bridgepoint/prebuild.py", line 1917, in <module>
[ERROR]     main()
[ERROR]   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/bridgepoint/prebuild.py", line 1911, in main
[ERROR]     prebuild_model(m)
[ERROR]   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/bridgepoint/prebuild.py", line 1876, in prebuild_model
[ERROR]     prebuild_action(inst)
[ERROR]   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/bridgepoint/prebuild.py", line 1854, in prebuild_action
[ERROR]     return walker.accept(root)
[ERROR]   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/xtuml/tools.py", line 220, in accept
[ERROR]     r = fn(node, **kwargs)
[ERROR]   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/bridgepoint/prebuild.py", line 1565, in accept_BodyNode
[ERROR]     return ActionPrebuilder.accept_BodyNode(self, node)
[ERROR]   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/bridgepoint/prebuild.py", line 439, in accept_BodyNode
[ERROR]     self.accept(node.block.statement_list)
[ERROR]   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/xtuml/tools.py", line 220, in accept
[ERROR]     r = fn(node, **kwargs)
[ERROR]   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/bridgepoint/prebuild.py", line 458, in accept_StatementListNode
[ERROR]     act_smt = self.accept(child)
[ERROR]   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/xtuml/tools.py", line 220, in accept
[ERROR]     r = fn(node, **kwargs)
[ERROR]   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/bridgepoint/prebuild.py", line 723, in accept_IfNode
[ERROR]     act_blk = self.accept(node.block)
[ERROR]   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/xtuml/tools.py", line 220, in accept
[ERROR]     r = fn(node, **kwargs)
[ERROR]   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/bridgepoint/prebuild.py", line 450, in accept_BlockNode
[ERROR]     self.accept(node.statement_list)
[ERROR]   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/xtuml/tools.py", line 220, in accept
[ERROR]     r = fn(node, **kwargs)
[ERROR]   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/bridgepoint/prebuild.py", line 458, in accept_StatementListNode
[ERROR]     act_smt = self.accept(child)
[ERROR]   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/xtuml/tools.py", line 220, in accept
[ERROR]     r = fn(node, **kwargs)
[ERROR]   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/bridgepoint/prebuild.py", line 1263, in accept_InvocationStatementNode
[ERROR]     self.accept(node.invocation, act_smt=act_smt)
[ERROR]   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/xtuml/tools.py", line 220, in accept
[ERROR]     r = fn(node, **kwargs)
[ERROR]   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/bridgepoint/prebuild.py", line 1275, in accept_ImplicitInvocationNode
[ERROR]     return self.accept_PortInvocationNode(node, act_smt=act_smt)
[ERROR]   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/bridgepoint/prebuild.py", line 1393, in accept_PortInvocationNode
[ERROR]     ProvidedSig_Id=spr_ps.Id)
[ERROR]   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/bridgepoint/prebuild.py", line 194, in new
[ERROR]     return self.m.new(*args, **kwargs)
[ERROR]   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/xtuml/meta.py", line 1197, in new
[ERROR]     return metaclass.new(*args, **kwargs)
[ERROR]   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/xtuml/meta.py", line 624, in new
[ERROR]     relate(other_inst, inst, link.rel_id, link.phrase)
[ERROR]   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/xtuml/meta.py", line 1005, in relate
[ERROR]     raise RelateException(from_instance, to_instance, rel_id, phrase)
[ERROR] xtuml.meta.RelateException: SPR_PS(Id="f0cf0b20-d2ce-4df6-8779-b7b5a949c8ed", Name='Reply', Descrip='', Action_Semantics_internal='', Suc_Pars=1, Dialect=0) or ACT_SGN(Statement_ID="37769166-a977-4428-8d90-35c99225c15c", sigNameLineNumber=0, sigNameColumn=0, ownerNameLineNumber=0, ownerNameColumn=0, ProvidedSig_Id="f0cf0b20-d2ce-4df6-8779-b7b5a949c8ed", RequiredSig_Id="00000000-0000-0000-0000-000000000000", Value_ID="00000000-0000-0000-0000-000000000000") already related across R663
[ERROR] pyxtuml exited with code 1

**Comment by johnrwolfe** [comment]
Please specify the repository and commit tag for which this error occurs, and I will investigate it.

**Comment by zydsh** [comment]
Hi John,

https://github.com/zydsh/hrm/tree/compiledFmsBudget

You might find at first that the fms (Financial Management System) does not load to BP. But I guess you can trace the changes from commit. Most of commits that have debugging are after the issue started to appear.

I have now moved on and got things working. I thought to register it for reference.   

Thanks

**Comment by johnrwolfe** [comment]
OK, then I suggest you close the issue since it is now working.  The issue will remain available (in the closed state) for future reference.
