### ISSUE TITLE
Attribute Error: When attempting to translate FMS integrated with UI

### ISSUE THREAD

**Issue by zydsh** [zydsh/hrm#5]
After compiling HRM with UI separately with no issues, adding the FMS component to Deployment resulted in the following error:

[ERROR] AttributeError: 'NoneType' object has no attribute 'Id'
[ERROR] pyxtuml exited with code 1

**Comment by johnrwolfe** [comment]
Ensure that the application.mark file still contains a line defining the root package.  A defect in the tooling causes that line  to be removed from the file occasionally.  So, we are all in habit of restoring the file from the HEAD revision when necessary.
Please paste the entire error listing into this issue, and I will try to work out the source of the problem.
